ALTER TABLE "CORE_ROLE_RIGHT_XREF" DISABLE CONSTRAINT "FK5AFA2427E35D2FF0";
ALTER TABLE "CORE_ROLE_RIGHT_XREF" DISABLE CONSTRAINT "FK5AFA2427FEB2F584";
UPDATE core_role_right_xref SET right_id = 'uploadcenter.author' WHERE right_id LIKE 'page.UploadCenterPage';
UPDATE core_right SET right_id = 'uploadcenter.author', description = 'Upload Center Author' WHERE right_id LIKE 'page.UploadCenterPage';
ALTER TABLE "CORE_ROLE_RIGHT_XREF" ENABLE CONSTRAINT "FK5AFA2427E35D2FF0";
ALTER TABLE "CORE_ROLE_RIGHT_XREF" ENABLE CONSTRAINT "FK5AFA2427FEB2F584";