CREATE TABLE "DOWNLOAD"
 (	"ID" NUMBER(10,0) NOT NULL ENABLE,
  "CREATED_AT" TIMESTAMP (6),
  "CREATED_BY" VARCHAR2(30 CHAR),
  "MODIFIED_AT" TIMESTAMP (6),
  "MODIFIED_BY" VARCHAR2(30 CHAR),
  "BROKEN" NUMBER(1,0),
  "DESCRIPTION" CLOB,
  "HITS" NUMBER(10,0),
  "NUMBER_OF_VOTES" NUMBER(10,0),
  "SUM_OF_RATING" NUMBER(10,0),
  "TITLE" VARCHAR2(255 CHAR),
  "URL" VARCHAR2(255 CHAR),
  "DOWNLOAD_SIZE" VARCHAR2(255 CHAR),
  "LICENCE" VARCHAR2(255 CHAR),
  "MANUFACTURER" VARCHAR2(255 CHAR),
  "MANUFACTURER_HOMEPAGE" VARCHAR2(255 CHAR),
  "PRICE" VARCHAR2(255 CHAR),
  "SOFTWARE_VERSION" VARCHAR2(255 CHAR),
   PRIMARY KEY ("ID") ENABLE
 );


CREATE TABLE "DOWNLOAD_RIGHT_XREF"
 (	"DOWNLOAD_ID" NUMBER(10,0) NOT NULL ENABLE,
  "RIGHT_ID" VARCHAR2(50 CHAR) NOT NULL ENABLE,
   CONSTRAINT "FK24629575D8DA64D7" FOREIGN KEY ("DOWNLOAD_ID")
    REFERENCES "DOWNLOAD" ("ID") ENABLE,
   CONSTRAINT "FK24629575FEB2F584" FOREIGN KEY ("RIGHT_ID")
    REFERENCES "CORE_RIGHT" ("RIGHT_ID") ENABLE
 );


CREATE TABLE "DOWNLOAD_TAG"
 (	"TAGNAME" VARCHAR2(255 CHAR) NOT NULL ENABLE,
  "CREATED_AT" TIMESTAMP (6),
  "CREATED_BY" VARCHAR2(30 CHAR),
  "MODIFIED_AT" TIMESTAMP (6),
  "MODIFIED_BY" VARCHAR2(30 CHAR),
   PRIMARY KEY ("TAGNAME") ENABLE
 );


CREATE TABLE "DOWNLOAD_TAG_XREF"
 (	"DOWNLOAD_ID" NUMBER(10,0) NOT NULL ENABLE,
  "TAGNAME" VARCHAR2(255 CHAR) NOT NULL ENABLE,
   CONSTRAINT "FKC76A7077D8DA64D7" FOREIGN KEY ("DOWNLOAD_ID")
    REFERENCES "DOWNLOAD" ("ID") ENABLE,
   CONSTRAINT "FKC76A7077544D7D40" FOREIGN KEY ("TAGNAME")
    REFERENCES "DOWNLOAD_TAG" ("TAGNAME") ENABLE
 );
