CREATE TABLE "BLOG"
 (	"ID" NUMBER(10,0) NOT NULL ENABLE,
  "CREATED_AT" TIMESTAMP (6),
  "CREATED_BY" VARCHAR2(30 CHAR),
  "MODIFIED_AT" TIMESTAMP (6),
  "MODIFIED_BY" VARCHAR2(30 CHAR),
  "CONTENT" CLOB,
  "HEADLINE" VARCHAR2(255 CHAR),
   PRIMARY KEY ("ID") ENABLE
 );

CREATE TABLE "BLOG_RIGHT_XREF"
 (	"BLOG_ID" NUMBER(10,0) NOT NULL ENABLE,
  "RIGHT_ID" VARCHAR2(50 CHAR) NOT NULL ENABLE,
   CONSTRAINT "FK21039A1B6C6A8F31" FOREIGN KEY ("BLOG_ID")
    REFERENCES "BLOG" ("ID") ENABLE,
   CONSTRAINT "FK21039A1BFEB2F584" FOREIGN KEY ("RIGHT_ID")
    REFERENCES "CORE_RIGHT" ("RIGHT_ID") ENABLE
 );


CREATE TABLE "BLOG_TAG"
 (	"TAGNAME" VARCHAR2(255 CHAR) NOT NULL ENABLE,
  "CREATED_AT" TIMESTAMP (6),
  "CREATED_BY" VARCHAR2(30 CHAR),
  "MODIFIED_AT" TIMESTAMP (6),
  "MODIFIED_BY" VARCHAR2(30 CHAR),
   PRIMARY KEY ("TAGNAME") ENABLE
 );


CREATE TABLE "BLOG_TAG_XREF"
 (	"BLOG_ID" NUMBER(10,0) NOT NULL ENABLE,
  "TAGNAME" VARCHAR2(255 CHAR) NOT NULL ENABLE,
   CONSTRAINT "FK3DB0669D6C6A8F31" FOREIGN KEY ("BLOG_ID")
    REFERENCES "BLOG" ("ID") ENABLE,
   CONSTRAINT "FK3DB0669D97F1D10C" FOREIGN KEY ("TAGNAME")
    REFERENCES "BLOG_TAG" ("TAGNAME") ENABLE
 );

 -- since 1.1
CREATE TABLE "BLOG_HISTORIZED"
 (
  "ID" NUMBER(10,0) NOT NULL ENABLE,
  "VERSION_NUMBER" NUMBER(10, 0) NOT NULL,
  "CREATED_AT" TIMESTAMP (6),
  "CREATED_BY" VARCHAR2(30),
  "MODIFIED_AT" TIMESTAMP (6),
  "MODIFIED_BY" VARCHAR2(30),
  "ACTION" VARCHAR2(50),
  "ACTION_AT" TIMESTAMP (6),
  "RESTORED_FROM_VERSION" NUMBER(10, 0),
  "CONTENT" CLOB,
  "HEADLINE" VARCHAR2(255),
  "TAGS" CLOB,
  "RIGHTS" CLOB,
  "BLOG_ID" NUMBER(10, 0) NOT NULL,
   PRIMARY KEY ("ID") ENABLE
 );
