CREATE TABLE blog
(
   id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
   created_at timestamp,
   created_by varchar(30),
   modified_at timestamp,
   modified_by varchar(30),
   content longvarchar,
   headline varchar(255),
   PRIMARY KEY(id)
)
;
CREATE TABLE blog_right_xref
(
   blog_id int NOT NULL,
   right_id varchar(50) NOT NULL
)
;
CREATE TABLE blog_tag
(
   tagname varchar(255) NOT NULL,
   created_at timestamp,
   created_by varchar(30),
   modified_at timestamp,
   modified_by varchar(30),
   PRIMARY KEY(tagname)
)
;
CREATE TABLE blog_tag_xref
(
   blog_id int NOT NULL,
   tagname varchar(255) NOT NULL
)
;

-- since 1.1
CREATE TABLE blog_historized (
  id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
  version_number int) NOT NULL,
  created_at timestamp default NULL,
  created_by varchar(30) default NULL,
  modified_at timestamp default NULL,
  modified_by varchar(30) default NULL,
  action varchar default NULL,
  action_at timestamp default NULL,
  restored_from_version int default NULL,
  content mediumtext,
  headline varchar(255) default NULL,
  tags text default NULL,
  rights text default NULL,
  blog_id int NOT NULL,
   PRIMARY KEY(id)
)
;