
CREATE TABLE "BOOKMARK"
 (	"ID" NUMBER(10,0) NOT NULL ENABLE,
  "CREATED_AT" TIMESTAMP (6),
  "CREATED_BY" VARCHAR2(30 CHAR),
  "MODIFIED_AT" TIMESTAMP (6),
  "MODIFIED_BY" VARCHAR2(30 CHAR),
  "BROKEN" NUMBER(1,0),
  "DESCRIPTION" CLOB,
  "HITS" NUMBER(10,0),
  "NUMBER_OF_VOTES" NUMBER(10,0),
  "SUM_OF_RATING" NUMBER(10,0),
  "TITLE" VARCHAR2(255 CHAR),
  "URL" VARCHAR2(255 CHAR),
  "SOURCE" VARCHAR2(255 CHAR),
  "SYNC_HASH" VARCHAR2(255 CHAR),
  "SYNC_USERNAME" VARCHAR2(255 CHAR),
   PRIMARY KEY ("ID") ENABLE
 );


CREATE TABLE "BOOKMARK_RIGHT_XREF"
 (	"BOOKMARK_ID" NUMBER(10,0) NOT NULL ENABLE,
  "RIGHT_ID" VARCHAR2(50 CHAR) NOT NULL ENABLE,
   CONSTRAINT "FK6B52A007BAE949C5" FOREIGN KEY ("BOOKMARK_ID")
    REFERENCES "BOOKMARK" ("ID") ENABLE,
   CONSTRAINT "FK6B52A007FEB2F584" FOREIGN KEY ("RIGHT_ID")
    REFERENCES "CORE_RIGHT" ("RIGHT_ID") ENABLE
 );


CREATE TABLE "BOOKMARK_TAG"
 (	"TAGNAME" VARCHAR2(255 CHAR) NOT NULL ENABLE,
  "CREATED_AT" TIMESTAMP (6),
  "CREATED_BY" VARCHAR2(30 CHAR),
  "MODIFIED_AT" TIMESTAMP (6),
  "MODIFIED_BY" VARCHAR2(30 CHAR),
   PRIMARY KEY ("TAGNAME") ENABLE
 );


CREATE TABLE "BOOKMARK_TAG_XREF"
 (	"BOOKMARK_ID" NUMBER(10,0) NOT NULL ENABLE,
  "TAGNAME" VARCHAR2(255 CHAR) NOT NULL ENABLE,
   CONSTRAINT "FKC59FF789BAE949C5" FOREIGN KEY ("BOOKMARK_ID")
    REFERENCES "BOOKMARK" ("ID") ENABLE,
   CONSTRAINT "FKC59FF78986BC2764" FOREIGN KEY ("TAGNAME")
    REFERENCES "BOOKMARK_TAG" ("TAGNAME") ENABLE
 );
