CREATE TABLE comment
(
   id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
   created_at timestamp,
   created_by varchar(30),
   modified_at timestamp,
   modified_by varchar(30),
   guest_name varchar(50),
   guest_email varchar(50),
   comment longvarchar  not null,
   ip_address varchar(39)  not null,
   number_of_blames int,
   accepted bit  not null,
   reviewed bit  not null,
   automatic_blocked bit not null,
   module_name varchar(20) not null,
   module_content_id varchar(20) not null,
   PRIMARY KEY(id)
)
;